name 'qmail'
maintainer 'DSI'
maintainer_email 'stephane.lii@informatique.gov.pf'
license 'All rights reserved'
description 'Installs/Configures qmail'
long_description 'Installs/Configures qmail'
version '0.1.0'
